spring.application.name=march_26_2026_Spring-Boot_Employee_Configuration_System_With_ConfigurationProperties_Annotation

employee.id=101
employee.name=Raj
employee.salary=45200

#Array
employee.skills=Java,html,python
#employee.skills[1]=HTML
#employee.skills[2]=Spring

#List
employee.projects[0]=Employee Management System
employee.projects[1]=Student Management System
employee.projects[2]=Hospital Management System

#Set
employee.tools=Docker,Dev

#Map
employee.experience.java=2
employee.experience.Python=3
employee.experience.Spring-boot=4

#Address Object
employee.address.city=Hydrabad
employee.address.state=Telngana
employee.address.pincode=400144


