spring.application.name=march_18_2026_Spring-Boot_02_ConfigurationProperties_Company_Department_List_System

company.departments[0].deptId=101
company.departments[0].deptName=HR

company.departments[1].deptId=102
company.departments[1].deptName=IT

company.departments[2].deptId=103
company.departments[2].deptName=Finances