spring.application.name=march_14_2026_Spring-Boot_test_Spring_Boot_Layered_Application_using_DataSource

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=c##sonu
spring.datasource.password=sonu