spring.application.name=march_16_2026_Spring-Boot_Console_Based_Application_for_Managing_Orders

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=c##sonu
spring.datasource.password=sonu