spring.application.name=CRUD_App_Layered_Application_Using_Plain_JDBC

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=c##sonu
spring.datasource.password=sonu