spring.application.name=march_11_2026_Spring-boot_LayeredApp-Mini-Project


spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=c##sonu
spring.datasource.password=sonu