spring.application.name=march_26_2026_Spring-Boot_Product_Inventory_System_With_ConfigurationProperties_Annotation

product.id=441122
product.name=Laptop
product.price=54000.00

#Array
product.features=High-Performance Processing,Long Battery Life,Enhanced Conferencing and Security

#List
product.categories=Signature 3:2 Display & Design,Performance & Processor Choice,Long-Lasting Battery Life,Premium Build & Audio

#Set
product.tags=Display,Performance,Battery,Design,Security

#Map
product.stock.Hydarabad=10
product.stock.Banglore=20
product.stock.Chennai=26
product.stock.Maharastra=60

#Supplier
product.supplier.name=Raju
product.supplier.location=Mubai
product.supplier.contact=7854859658



