spring.application.name=march_26_2026_Spring-Boot_Student_Course_Management_System_With_ConfigurationProperties_Annotation

student.id=101
student.name=Rahul
student.course=Java Full Stack

#Array
student.hobbies=Reading,Cricket,Cooking

#List
student.subjects=HTML, Core-Java, Adv-Java, Sprng, Spring-boot

#Set
student.certifications=Java Developer, Spring-boot Developer

#Map
student.marks.html=75
student.marks.css=55
student.marks.java=85
student.marks.Spring=95

#Address Object
student.address.city=Ranchi
student.address.state=Jharkhand
student.address.pincode=834001