spring.application.name=march_18_2026_Spring-Boot_05_ConfigurationProperties_Library_Map_System

library.books.java=Effective Java
library.books.Spring=Spring in Action
library.books.Python=Learning Python
